# Generated by Django 5.2.7 on 2025-11-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_hash_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
