# Generated by Django 5.2.7 on 2025-11-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
